name: Trigger auto deployment for kurzschlussfestigkeit

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ deployment ]
    paths:
    - '**'
    - '.github/workflows/kurzschlussfestigkeit-AutoDeployTrigger-a0b85717-0174-404d-90f9-b0b83d7f2e42.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KURZSCHLUSSFESTIGKEIT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KURZSCHLUSSFESTIGKEIT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KURZSCHLUSSFESTIGKEIT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.KURZSCHLUSSFESTIGKEIT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KURZSCHLUSSFESTIGKEIT_REGISTRY_PASSWORD }}
          containerAppName: kurzschlussfestigkeit
          resourceGroup: Ressourcengruppe_Container_Apps
          imageToBuild: kalandor/kurzschlussfestigkeit:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


